/** 미국 주요 거래소 (FMP `exchangeShortName` 등과 맞춤) */
export const EXCHANGE_FALLBACK = [
  { value: '', label: '거래소 전체' },
  { value: 'NASDAQ', label: 'NASDAQ' },
  { value: 'NYSE', label: 'NYSE' },
  { value: 'AMEX', label: 'AMEX' },
] as const;

/**
 * FMP 스크리너 `country` (ISO 3166-1 alpha-2). 메타/목록 API 실패 시 드롭다운용.
 * 전체 목록은 API로 보강하는 것을 권장.
 */
export const COUNTRY_FALLBACK = [
  { value: '', label: '국가 전체' },
  { value: 'US', label: '미국' },
  { value: 'CA', label: '캐나다' },
  { value: 'GB', label: '영국' },
  { value: 'DE', label: '독일' },
  { value: 'FR', label: '프랑스' },
  { value: 'JP', label: '일본' },
  { value: 'CN', label: '중국' },
  { value: 'HK', label: '홍콩' },
  { value: 'IN', label: '인도' },
  { value: 'AU', label: '호주' },
  { value: 'BR', label: '브라질' },
  { value: 'CH', label: '스위스' },
  { value: 'SE', label: '스웨덴' },
  { value: 'NL', label: '네덜란드' },
  { value: 'IT', label: '이탈리아' },
  { value: 'ES', label: '스페인' },
  { value: 'KR', label: '한국' },
  { value: 'SG', label: '싱가포르' },
  { value: 'TW', label: '대만' },
  { value: 'MX', label: '멕시코' },
  { value: 'ZA', label: '남아프리카공화국' },
  { value: 'IE', label: '아일랜드' },
  { value: 'IL', label: '이스라엘' },
  { value: 'BE', label: '벨기에' },
  { value: 'AT', label: '오스트리아' },
  { value: 'DK', label: '덴마크' },
  { value: 'FI', label: '핀란드' },
  { value: 'NO', label: '노르웨이' },
  { value: 'NZ', label: '뉴질랜드' },
  { value: 'PL', label: '폴란드' },
  { value: 'PT', label: '포르투갈' },
  { value: 'TH', label: '태국' },
  { value: 'MY', label: '말레이시아' },
  { value: 'ID', label: '인도네시아' },
  { value: 'PH', label: '필리핀' },
  { value: 'AE', label: '아랍에미리트' },
  { value: 'SA', label: '사우디아라비아' },
  { value: 'TR', label: '튀르키예' },
  { value: 'AR', label: '아르헨티나' },
  { value: 'CL', label: '칠레' },
  { value: 'CO', label: '콜롬비아' },
  { value: 'GR', label: '그리스' },
  { value: 'CZ', label: '체코' },
  { value: 'HU', label: '헝가리' },
  { value: 'RO', label: '루마니아' },
  { value: 'RU', label: '러시아' },
  { value: 'VN', label: '베트남' },
  { value: 'PE', label: '페루' },
  { value: 'PA', label: '파나마' },
  { value: 'UY', label: '우루과이' },
  { value: 'LU', label: '룩셈부르크' },
  { value: 'BM', label: '버뮤다' },
  { value: 'KY', label: '케이맨 제도' },
  { value: 'CY', label: '키프로스' },
  { value: 'IS', label: '아이슬란드' },
  { value: 'MT', label: '몰타' },
  { value: 'MC', label: '모나코' },
  { value: 'JO', label: '요르단' },
  { value: 'KZ', label: '카자흐스탄' },
] as const;

/** FMP 메타 API 실패 시 섹터 드롭다운용 (GICS 스타일, FMP 스크리너와 대체로 동일) */
export const SECTOR_FALLBACK = [
  { value: '', label: '업종 전체' },
  { value: 'Basic Materials', label: '기초 소재' },
  { value: 'Communication Services', label: '커뮤니케이션 서비스' },
  { value: 'Consumer Cyclical', label: '경기 소비재' },
  { value: 'Consumer Defensive', label: '필수 소비재' },
  { value: 'Energy', label: '에너지' },
  { value: 'Financial Services', label: '금융 서비스' },
  { value: 'Healthcare', label: '헬스케어' },
  { value: 'Industrials', label: '산업재' },
  { value: 'Real Estate', label: '부동산' },
  { value: 'Technology', label: '정보기술(IT)' },
  { value: 'Utilities', label: '공익사업' },
] as const;

/**
 * FMP `available-industries` 실패 시 산업 드롭다운용.
 * Finviz / FMP 스크리너 공식 분류 기준 (v2025 확인).
 * 전체 목록은 API로 보강하는 것을 권장.
 */
export const INDUSTRY_FALLBACK = [
  { value: '', label: '산업 전체' },
  { value: 'Advertising Agencies', label: '광고 대행사' },
  { value: 'Aerospace & Defense', label: '항공우주 및 방위' },
  { value: 'Agricultural Inputs', label: '농업 투입재' },
  { value: 'Airlines', label: '항공사' },
  { value: 'Airports & Air Services', label: '공항 및 항공 서비스' },
  { value: 'Aluminum', label: '알루미늄' },
  { value: 'Apparel Manufacturing', label: '의류 제조' },
  { value: 'Apparel Retail', label: '의류 소매' },
  { value: 'Asset Management', label: '자산 운용' },
  { value: 'Auto & Truck Dealerships', label: '자동차 및 트럭 딜러' },
  { value: 'Auto Manufacturers', label: '자동차 제조사' },
  { value: 'Auto Parts', label: '자동차 부품' },
  { value: 'Banks - Diversified', label: '은행 - 종합' },
  { value: 'Banks - Regional', label: '지역 은행' },
  { value: 'Beverages - Brewers', label: '음료 - 맥주 양조' },
  { value: 'Beverages - Non-Alcoholic', label: '음료 - 비알코올' },
  {
    value: 'Beverages - Wineries & Distilleries',
    label: '음료 - 와인 및 증류주',
  },
  { value: 'Biotechnology', label: '바이오테크놀로지' },
  { value: 'Broadcasting', label: '방송' },
  { value: 'Building Materials', label: '건축 자재' },
  { value: 'Building Products & Equipment', label: '건축 제품 및 장비' },
  { value: 'Business Equipment & Supplies', label: '사무용 장비 및 소모품' },
  { value: 'Capital Markets', label: '자본 시장' },
  { value: 'Chemicals', label: '화학' },
  { value: 'Coking Coal', label: '코킹용 석탄' },
  { value: 'Communication Equipment', label: '통신 장비' },
  { value: 'Computer Hardware', label: '컴퓨터 하드웨어' },
  { value: 'Confectioners', label: '제과·제빵' },
  { value: 'Conglomerates', label: '복합 기업' },
  { value: 'Consulting Services', label: '컨설팅 서비스' },
  { value: 'Consumer Electronics', label: '소비자 가전' },
  { value: 'Copper', label: '구리' },
  { value: 'Credit Services', label: '신용 서비스' },
  { value: 'Department Stores', label: '백화점' },
  { value: 'Diagnostics & Research', label: '진단 및 연구' },
  { value: 'Discount Stores', label: '할인점' },
  { value: 'Drug Manufacturers - General', label: '제약 - 일반' },
  {
    value: 'Drug Manufacturers - Specialty & Generic',
    label: '제약 - 전문·제네릭',
  },
  { value: 'Education & Training Services', label: '교육 및 훈련 서비스' },
  { value: 'Electrical Equipment & Parts', label: '전기 장비 및 부품' },
  { value: 'Electronic Components', label: '전자 부품' },
  { value: 'Electronic Gaming & Multimedia', label: '전자 게임 및 멀티미디어' },
  { value: 'Electronics & Computer Distribution', label: '전자·컴퓨터 유통' },
  { value: 'Engineering & Construction', label: '엔지니어링 및 건설' },
  { value: 'Entertainment', label: '엔터테인먼트' },
  {
    value: 'Farm & Heavy Construction Machinery',
    label: '농업 및 건설 중장비',
  },
  { value: 'Farm Products', label: '농산물' },
  { value: 'Financial Conglomerates', label: '금융 복합 기업' },
  {
    value: 'Financial Data & Stock Exchanges',
    label: '금융 데이터 및 증권 거래소',
  },
  { value: 'Food Distribution', label: '식품 유통' },
  { value: 'Footwear & Accessories', label: '신발 및 잡화' },
  {
    value: 'Furnishings, Fixtures & Appliances',
    label: '가구·인테리어 및 가전제품',
  },
  { value: 'Gambling', label: '도박' },
  { value: 'Gold', label: '금(金)' },
  { value: 'Grocery Stores', label: '식료품점' },
  { value: 'Health Information Services', label: '건강 정보 서비스' },
  { value: 'Healthcare Plans', label: '건강보험' },
  { value: 'Home Improvement Retail', label: '주택 인테리어 소매' },
  { value: 'Household & Personal Products', label: '가정·개인용 제품' },
  { value: 'Industrial Distribution', label: '산업용품 유통' },
  { value: 'Information Technology Services', label: '정보기술(IT) 서비스' },
  { value: 'Insurance - Diversified', label: '보험 - 종합' },
  { value: 'Insurance - Life', label: '보험 - 생명' },
  { value: 'Insurance - Property & Casualty', label: '보험 - 손해' },
  { value: 'Insurance - Reinsurance', label: '보험 - 재보험' },
  { value: 'Insurance - Specialty', label: '보험 - 특수' },
  { value: 'Insurance Brokers', label: '보험 중개사' },
  { value: 'Integrated Freight & Logistics', label: '통합 화물 및 물류' },
  { value: 'Internet Content & Information', label: '인터넷 콘텐츠 및 정보' },
  { value: 'Internet Retail', label: '인터넷 소매' },
  { value: 'Leisure', label: '레저' },
  { value: 'Lodging', label: '숙박업' },
  { value: 'Lumber & Wood Production', label: '목재 생산' },
  { value: 'Luxury Goods', label: '명품·사치품' },
  { value: 'Marine Shipping', label: '해운' },
  { value: 'Medical Care Facilities', label: '의료 시설' },
  { value: 'Medical Devices', label: '의료 기기' },
  { value: 'Medical Distribution', label: '의료용품 유통' },
  { value: 'Medical Instruments & Supplies', label: '의료 기구 및 소모품' },
  { value: 'Metal Fabrication', label: '금속 가공' },
  { value: 'Mortgage Finance', label: '주택 담보 금융' },
  { value: 'Oil & Gas Drilling', label: '석유·가스 시추' },
  { value: 'Oil & Gas E&P', label: '석유·가스 탐사 및 생산' },
  {
    value: 'Oil & Gas Equipment & Services',
    label: '석유·가스 장비 및 서비스',
  },
  { value: 'Oil & Gas Integrated', label: '석유·가스 통합' },
  { value: 'Oil & Gas Midstream', label: '석유·가스 중류(Midstream)' },
  {
    value: 'Oil & Gas Refining & Marketing',
    label: '석유·가스 정제 및 마케팅',
  },
  {
    value: 'Other Industrial Metals & Mining',
    label: '기타 산업용 금속 및 채굴',
  },
  { value: 'Other Precious Metals & Mining', label: '기타 귀금속 및 채굴' },
  { value: 'Packaged Foods', label: '포장 식품' },
  { value: 'Packaging & Containers', label: '포장재 및 용기' },
  { value: 'Paper & Paper Products', label: '종이 및 종이 제품' },
  { value: 'Personal Services', label: '개인 서비스' },
  { value: 'Pharmaceutical Retailers', label: '제약 소매(약국 체인)' },
  { value: 'Pollution & Treatment Controls', label: '오염 방제 및 처리 설비' },
  { value: 'Publishing', label: '출판' },
  { value: 'Railroads', label: '철도' },
  { value: 'Real Estate - Development', label: '부동산 개발' },
  { value: 'Real Estate - Diversified', label: '부동산 - 종합' },
  { value: 'Real Estate Services', label: '부동산 서비스' },
  { value: 'Recreational Vehicles', label: '레저용 차량(RV)' },
  { value: 'REIT - Diversified', label: 'REIT - 종합' },
  { value: 'REIT - Healthcare Facilities', label: 'REIT - 의료 시설' },
  { value: 'REIT - Hotel & Motel', label: 'REIT - 호텔·모텔' },
  { value: 'REIT - Industrial', label: 'REIT - 산업용' },
  { value: 'REIT - Mortgage', label: 'REIT - 모기지' },
  { value: 'REIT - Office', label: 'REIT - 오피스' },
  { value: 'REIT - Residential', label: 'REIT - 주거용' },
  { value: 'REIT - Retail', label: 'REIT - 리테일' },
  { value: 'REIT - Specialty', label: 'REIT - 특수 목적' },
  { value: 'Rental & Leasing Services', label: '렌탈 및 리스 서비스' },
  { value: 'Residential Construction', label: '주거용 건설' },
  { value: 'Resorts & Casinos', label: '리조트 및 카지노' },
  { value: 'Restaurants', label: '음식점' },
  { value: 'Scientific & Technical Instruments', label: '과학·기술 계측 장비' },
  { value: 'Security & Protection Services', label: '보안 및 경호 서비스' },
  {
    value: 'Semiconductor Equipment & Materials',
    label: '반도체 장비 및 소재',
  },
  { value: 'Semiconductors', label: '반도체' },
  { value: 'Shell Companies', label: '쉘 컴퍼니' },
  { value: 'Silver', label: '은(銀)' },
  { value: 'Software - Application', label: '소프트웨어 - 응용' },
  { value: 'Software - Infrastructure', label: '소프트웨어 - 인프라' },
  { value: 'Solar', label: '태양광' },
  { value: 'Specialty Business Services', label: '특수 비즈니스 서비스' },
  { value: 'Specialty Chemicals', label: '특수 화학' },
  { value: 'Specialty Industrial Machinery', label: '특수 산업 기계' },
  { value: 'Specialty Retail', label: '전문 소매' },
  {
    value: 'Staffing & Employment Services',
    label: '인력 파견 및 채용 서비스',
  },
  { value: 'Steel', label: '철강' },
  { value: 'Telecom Services', label: '통신 서비스' },
  { value: 'Textile Manufacturing', label: '섬유 제조' },
  { value: 'Thermal Coal', label: '발전용 석탄' },
  { value: 'Tobacco', label: '담배' },
  { value: 'Tools & Accessories', label: '공구 및 액세서리' },
  { value: 'Travel Services', label: '여행 서비스' },
  { value: 'Trucking', label: '트럭 운송' },
  { value: 'Uranium', label: '우라늄' },
  { value: 'Utilities - Diversified', label: '공익사업 - 종합' },
  {
    value: 'Utilities - Independent Power Producers',
    label: '공익사업 - 독립 발전사업자',
  },
  { value: 'Utilities - Regulated Electric', label: '공익사업 - 규제 전기' },
  { value: 'Utilities - Regulated Gas', label: '공익사업 - 규제 가스' },
  { value: 'Utilities - Regulated Water', label: '공익사업 - 규제 수도' },
  { value: 'Utilities - Renewable', label: '공익사업 - 재생에너지' },
  { value: 'Waste Management', label: '폐기물 관리' },
] as const;
